#!/bin/bash

if [ -f /home/nobody/vpn_incoming_port.txt ]; then
	# get port number assigned from pia's api (file contents generated by /root/getvpnport.sh)
	VPN_INCOMING_PORT=$(</home/nobody/vpn_incoming_port.txt)
else
	VPN_INCOMING_PORT=""
fi
