#!/bin/bash

while [ ! -f /home/nobody/vpn_incoming_port.txt ]
do
	sleep 0.1s
done

# get port number assigned from pia's api (file contents generated by /root/getvpnport.sh)
VPN_INCOMING_PORT=$(</home/nobody/vpn_incoming_port.txt)

if [[ -z "${VPN_INCOMING_PORT}" ]]; then
	echo "[warn] Port forwarding is already activated on this connection, has expired, or you are NOT connected to a PIA region that supports port forwarding"
else
	if [[ "${DEBUG}" == "true" ]]; then
		echo "[debug] Incoming port for tunnel is '${VPN_INCOMING_PORT}'"
	fi
fi
