#!/bin/bash

while [ ! -f /home/nobody/vpn_incoming_port.txt ]
do
	sleep 0.1s
done

# get port number assigned from pia's api (file contents generated by /root/getvpnport.sh)
VPN_INCOMING_PORT=$(</home/nobody/vpn_incoming_port.txt)
