#!/bin/bash

# this script reads in the contents of a temporary file which 
# contains the ip address for the name lookup for the argument
# sent to the script /root/checkdns.sh. the file /tmp/checkdns
# is generated by the script /root/checkdns.sh and is removed
# at startup via the init.sh script. we use the temporary file
# to verify dns is operational before the application starts.

# function to verify dns resolution is operational
check_dns() {

	# check /tmp/checkdns file exists
	if [ ! -f /tmp/checkdns ]; then
		return 1
	fi

	cat /tmp/checkdns | grep -oqE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' || return 1

	return 0
}

# loop and wait until dns resolution is operational
while ! check_dns
do
	sleep 0.1
done
