#!/bin/bash

# check that app requires external ip
if [[ "${APPLICATION}" != "sabnzbd" ]] && [[ "${APPLICATION}" != "privoxy" ]]; then

	while [ ! -f /tmp/getvpnextip ]
	do
		sleep 0.1s
	done

	# get vpn external ip address (file contents generated by /root/getvpnextip.sh)
	external_ip=$(</tmp/getvpnextip)

fi
