#!/bin/bash

while [ ! -f /tmp/getvpnextip ]
do
	sleep 0.1s
done

# get vpn external ip address (file contents generated by /root/getvpnextip.sh)
external_ip=$(</tmp/getvpnextip)

if [[ "${external_ip}" == "0.0.0.0" ]]; then
	echo "[warn] Cannot determine external IP address, possible connection issues at present."
else
	if [[ "${DEBUG}" == "true" ]]; then
		echo "[debug] External IP address from tunnel is '${external_ip}'"
	fi
fi
