#!/bin/bash

# script to call multiple scripts in series to read in values written by script /root/prerunget.sh

function source_tools() {
  # source in various tools
  # shellcheck source=../local/tools.sh
  source tools.sh
}

function check_tunnel_ip() {
  # blocking script, will wait for valid ip address assigned to tun0/tap0 (ip read in from file /tmp/getvpnip)
  # value read in is generated by script tools.sh
  check_vpn_tunnel_ip
}

function check_incoming_port() {
  # blocking script, will wait for vpn incoming port to be assigned (port read in from file /tmp/getvpnport)
  # value read in is generated by script tools.sh
  check_vpn_incoming_port
}

function verify_dns() {
  # blocking script, will wait for name resolution to be operational (will write to /tmp/dnsfailure if failure)
  check_dns www.google.com
}

function check_external_ip() {
  # blocking script, will wait for external ip address retrieval (external ip read in from file /tmp/getvpnextip)
  # value read in is generated by script tools.sh/get_vpn_external_ip
  check_vpn_external_ip
}

function verify_iptables() {
  # blocking script, will wait for iptables chain policy to be DROP (iptables listing read in from file /tmp/getiptables)
  # value read in is generated by script /root/iptable.sh
  check_iptables
}

function main() {
  source_tools
  check_tunnel_ip
  check_incoming_port
  verify_dns
  check_external_ip
  verify_iptables
}

main
