#!/bin/bash

# script to call multiple scripts in series to read in values written by script /root/prerunget.sh

# blocking script, will wait for valid ip address assigned to tun0/tap0
source /home/nobody/getvpnip.sh

# blocking script, will wait for vpn incoming port to be assigned (port read in from file /tmp/getvpnport)
# value read in is generated by script /root/getvpnport.sh
source /home/nobody/getvpnport.sh

# blocking script, will wait for name resolution to be operational (ip address from resolved host read in from file /tmp/checkdns)
# value read in is generated by script /root/checkdns.sh
source /home/nobody/checkdns.sh

# blocking script, will wait for external ip address retrieval (external ip read in from file /tmp/getvpnextip)
# value read in is generated by script /root/getvpnextip.sh
source /home/nobody/getvpnextip.sh

# blocking script, will wait for iptables chain policy to be DROP (iptables listing read in from file /tmp/checkiptables)
# value read in is generated by script /root/iptable.sh
source /home/nobody/checkiptables.sh
